### ISSUE TITLE
No USB Adapter passthrough

### ISSUE THREAD

**Issue by fresca25** [txhaflaire/DiskEncrypter#1]
I've noticed on M1 (Do not have intel with USB-A) that plugging a drive in using a USB-C adapter/dongle does not prompt DiskEncrypter to check if encrypted. Only when I plug in a direct connection via USB-C will it register to run the script then prompt. It is not specific to any adapter.

**Comment by txhaflaire** [comment]
@fresca25 
Thanks for reporting this issue, by providing issues we can make DiskEncrypter more robust!

I could not replicate this behaviour with the following equipment, in my case each time DiskEncrypter triggered the workflow.

Could you please provide some logs and if possible screenshots?

**External Media tested:**
Kensington USB-C thumbdrive (unencrypted)
Sandisk USB-A thumbdrive (unencrypted)

**Dongels tested:**
Apple USB-C to USB-A
Apple USB-C Multi media Adapter
Ugreen USB-C Multi media adapter
Apple wired keyboard USB-A to USB-A

**OS Versions tested:**
macOS Monterey 12.5
macOS Ventura 13.1


**Hardware tested:**
M1 Mac Mini
M1 MacBook Pro
Intel-based MacBook Pro

![Ventura_DiskEncrypter_USBCAdapter](https://user-images.githubusercontent.com/26306960/209788431-a305304d-bd65-4419-80f2-f6831596dd7a.png)
![Monterey_DiskEncrypter_USBCAdapter](https://user-images.githubusercontent.com/26306960/209788436-d498daee-d3f8-4dd8-81fa-bdb614f3082c.jpg)
