### ISSUE TITLE
Volume Device ID

### ISSUE THREAD

**Issue by Dinnerticketboy** [txhaflaire/DiskEncrypter#2]
Within the script I'd noticed you hard code either s1 or s2 to the end of $DiskID to get the volume device id.
I found that this doesn't always work, so I've replaced it to find the ID directly using:

VolumeID=$(df -h | grep $DiskID | awk '{print $1}' | sed 's/\/dev\///'))

Well done on all the work you have done on this 🥇

**Comment by txhaflaire** [comment]
@Dinnerticketboy Thanks for reporting in - could you submit an PR to collaborate on the code?

Thanks again :)

**Comment by txhaflaire** [comment]
Resolved in v1.3
