### ISSUE TITLE
Activates when DMGs are mounted

### ISSUE THREAD

**Issue by azgmacos** [txhaflaire/DiskEncrypter#6]
I really love this tool but it has started prompting when DMGs are mounted. I know technically an external drive could be mounted as a disk image, but this does have some undesired behavior for end users... Any thoughts on this?

**Comment by txhaflaire** [comment]
@azgmacos Thanks! do you have some logs available? either from capturing the Unified Logging or screenshots with some evidence?

On the top of the script it's basically hardcode that the device/volume needs to be external and physical so i'm curious where it's failing

[        if [[ -z $ExternalDisks ]]; then](https://github.com/txhaflaire/DiskEncrypter/blob/5db25b6b42deedc73f063e7d61a6810e5939ce96/DiskEncrypter.sh#L95)

**Comment by sdagley** [comment]
Using the Mac Eval Utility as a test case, when I mount the .dmg I'm seeing two entries in the diskutil list:
/dev/disk4 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +24.5 MB    disk4
   1:                 Apple_APFS Container disk5         24.5 MB    disk4s1

/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +24.5 MB    disk5
                                 Physical Store disk4s1
   1:                APFS Volume Mac Evaluation Utility  12.8 MB    disk5s1

No sign of an External reference at all, but there is a "Physical Store"
